language: R
sudo: false
cache: packages
latex: false
warnings_are_errors: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes'

after_success:
  - Rscript -e 'covr::codecov()'
