language: r
dist: trusty

branches:
  only:
  - master

r:
  - release
  - devel

r_build_args: --no-build-vignettes

os:
  - linux
  - osx

jobs:
  exclude:
    - os: osx
      r: devel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir -p ~/.R; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --yes --force-yes update -qq; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install build-essential software-properties-common; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install gcc-snapshot; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev curl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install udunits; fi;

install:
  - R -e "install.packages('remotes'); suppressWarnings(remotes::install_deps(dependencies = TRUE))"
  - R -e "install.packages(c('covr', 'rmarkdown', 'testthat'))"

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov()'; fi;
