---
title: "stem-vignette-advanced"
author: "Daniel Fink, Wesley Hochachka, Frank La Sorte, Tom Auer"
date: "9/25/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mapping Abundance

With a good full-annual extent and color bins, that accurately represent the data distribution, we can add in other pieces of data that represent predicted and assumed zeroes, which help display the extent of estimation.

```{r plot_es}
# pull in species-specific ensemble support, represent predicted 0s where there is no abundance value
pos_es_stack <- stack_stem(sp_path, variable = "abundance_ensemble_support")
week26_pes <- raster::projectRaster(pos_es_stack[[26]], crs = mollweide)

# to represent assumed 0s, we have provided the data object zero_es_stack
# that has values for the ensemble support indicating sufficient checklists
# to fit and predict models at that location
# for presentation we use a value of 99 to show locations with assumed 0s
zero_es_stack
week26_zes_vals <- raster::projectRaster(raster::mask(zero_es_stack[[26]], 
                                                 template_raster), 
                                    crs = mollweide)

# we'll combine the two types of zeroes with the positive prediction for plotting
week26_pes[week26_pes] <- 0
week26_zes <- week26_zes_vals >= 99
week26_zes[week26_zes == 0] <- NA
week26_zes[week26_zes == 1] <- 0

week26s <- raster::stack(week26_pes, week26_zes, week26_moll)
week26c <- raster::calc(week26s, max, na.rm = TRUE)

# to add context, let's pull in some reference data to add
wh <- rnaturalearth::ne_countries(continent = c("North America",
                                                "South America"))
wh_states <- rnaturalearth::ne_states(iso_a2 = unique(wh@data$iso_a2))
wh_moll <- sp::spTransform(wh, mollweide)
wh_states_moll <- sp::spTransform(wh_states, mollweide)

par(mar = c(0,0,0,2))
raster::plot(week26c, 
             xaxt = 'n', 
             yaxt = 'n',
             bty = 'n',
             ext = sp_ext_moll, 
             breaks = year_bins,
             lab.breaks = bin_labels,
             col = viridis(length(year_bins)-1),
             maxpixels = raster::ncell(week26c),
             legend = TRUE)
sp::plot(wh_moll, add = TRUE, border = 'gray')
sp::plot(wh_states_moll, add = TRUE, border = 'gray', lwd = 0.5)
```
