# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
tom_med <- function(x) {
    .Call('_ebirdst_tom_med', PACKAGE = 'ebirdst', x)
}

